[[plugins]]
repo = 'wsdjeg/dein-ui.vim'  " Install UI

[[plugins]]
repo = 'itchyny/lightline.vim'  " Status Line

[[plugins]]
repo = 'mengelbrecht/lightline-bufferline'  " Top buffer

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'deoplete-plugins/deoplete-jedi'  " Completion

[[plugins]]
repo = '/usr/local/opt/fzf'  " fzf vim-plugin


